<?php

require dirname(__DIR__) . '/vendor/autoload.php';

use CoffeeCode\Router\Router;

 $router = Router::auto();

// Optional: serve static assets safely (enable if you have a ./public folder)
// $router->setAssets(__DIR__ . '/public')->setCache(3600);

// Home page linking to the bundled examples
$router->get('/', function (array $data, Router $r) {
    echo "<h1>CoffeeCode Router Examples</h1>";
    echo "<p>Autonomous routing is enabled. No .htaccess or Nginx needed.</p>";
    echo "<ul>";
    echo "<li><a href='{$r->home()}/controller/'>Controller example</a></li>";
    echo "<li><a href='{$r->home()}/spoofing/'>Form spoofing example</a></li>";
    echo "<li><a href='{$r->home()}/api/'>API example (GET/POST, JSON, constraints)</a></li>";
    echo "<li><a href='{$r->home()}/webhook/'>Webhook example (POST with HMAC)</a></li>";
    echo "<li><a href='{$r->home()}/assets/'>Assets example (CSS/JS via Router)</a></li>";
    echo "<li><a href='{$r->home()}/health'>Health (HEAD/GET)</a></li>";
    echo "</ul>";
});

// Simple health endpoint
$router->get('/health', function () {
    header('Content-Type: text/plain');
    echo 'OK';
});

// HEAD support for health (headers only, no body)
$router->head('/health', function () {
    header('Content-Type: text/plain');
});

// OPTIONS (Allow header is also auto-generated by the router)
$router->options('/health', function () {
    // no body
});

// Execute routes
$router->dispatch();

// Basic error handling
if ($router->error()) {
    http_response_code($router->error());
    echo "Error: " . $router->error();
}